# Site settings
title: "HomePage | M. A. Heydari"
description: "Mohammad Ali Heydaries HomePage"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mohammad A. Heydari"
resume_title:                   "Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ostadgeorge@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+(98) 911-581-4641"
resume_contact_address:         "Iran, Mazandaran, Sari"

resume_header_contact_info:     "Iran, Mazandaran, Sari • +(98) 911-581-4641 • ostadgeorge@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi!<br>My name is Mohammad Ali Heyadri. I'm a computer science student in bachelor program of <a href='https://aut.ac.ir/'>Amirkabir University of Technology</a>, and I'm interested in anything which is related to learning! (e.g. Deep Learning, Machine Learning, Reinforcement Learning, Bandit Learing, Federated learning, ...).<br><br>Here you can find my <a href='https://github.com/ostadgeorge/ostadgeorge.github.io/raw/gh-pages/asset/cv.pdf'>CV</a>.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:          true
resume_section_education:           true
resume_section_projects:            true
resume_section_skills:              true
resume_section_recognition:         true
resume_section_links:               true
resume_section_associations:        true
resume_section_research_interests:  true
resume_section_honors_awards:       true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ostadgeorge/"
  resume_twitter_url:           "http://twitter.com/ostadgeorge"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mohammad-ali-heydari-a998801b3/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://ostadgeorge.github.io/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
